'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TryHTML.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;iframe width=&quot;420&quot; height=&quot;315&quot;
        '''src=&quot;https://www.youtube.com/embed/XGSy3_Czz8k?playlist=XGSy3_Czz8k&amp;loop=1&quot;&gt;
        '''&lt;/iframe&gt;.
        '''</summary>
        Friend ReadOnly Property _Loop() As String
            Get
                Return ResourceManager.GetString("_Loop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à a href=javascriptwindow.external.AddFavorite(&apos;httpwww.yoursite.com&apos;, &apos;Your Site Name&apos;)Add to Favoritesa
        '''//Source : http://www.htmlgoodies.com/beyond/javascript/article.php/3887346/Top-10-JavaScript-Snippets-for-Common-Tasks.htm.
        '''</summary>
        Friend ReadOnly Property Add_to_Favorites() As String
            Get
                Return ResourceManager.GetString("Add_to_Favorites", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;body&gt;
        '''
        '''&lt;p&gt;If a browser cannot find an image, it will display the alternate text:&lt;/p&gt;
        '''
        '''&lt;img src=&quot;wrongname.gif&quot; alt=&quot;HTML5 Icon&quot; style=&quot;width:128px;height:128px;&quot;&gt;
        '''
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property alt_Attribute() As String
            Get
                Return ResourceManager.GetString("alt_Attribute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;audio controls&gt;
        '''  &lt;source src=&quot;horse.ogg&quot; type=&quot;audio/ogg&quot;&gt;
        '''  &lt;source src=&quot;horse.mp3&quot; type=&quot;audio/mpeg&quot;&gt;
        '''Your browser does not support the audio element.
        '''&lt;/audio&gt;.
        '''</summary>
        Friend ReadOnly Property Audio() As String
            Get
                Return ResourceManager.GetString("Audio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;iframe width=&quot;420&quot; height=&quot;315&quot;
        '''src=&quot;https://www.youtube.com/embed/XGSy3_Czz8k?autoplay=1&quot;&gt;
        '''&lt;/iframe&gt;.
        '''</summary>
        Friend ReadOnly Property Auto_Play() As String
            Get
                Return ResourceManager.GetString("Auto_Play", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;FORM&gt;
        '''&lt;INPUT TYPE=&quot;Button&quot; VALUE=&quot;Previous Page&quot; onClick=&quot;history.go(-1)&quot;&gt;
        '''&lt;/FORM&gt;
        '''//If you would rather use a link, paste the following code where you want the link to appear:
        '''&lt;a href=&quot;javascript:history.back(1)&quot;&gt;Previous Page&lt;/a&gt; 
        '''//Source : http://www.htmlgoodies.com/beyond/javascript/article.php/3887346/Top-10-JavaScript-Snippets-for-Common-Tasks.htm.
        '''</summary>
        Friend ReadOnly Property Back_Button() As String
            Get
                Return ResourceManager.GetString("Back_Button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;p&gt;This is a paragraph.&lt;/p&gt;
        '''&lt;p&gt;This is another paragraph.&lt;/p&gt;.
        '''</summary>
        Friend ReadOnly Property Basic() As String
            Get
                Return ResourceManager.GetString("Basic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property books() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("books", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;style type=&quot;text/css&quot;&gt;
        '''span.label {color:black;width:30;height:16;text-align:center;margin-top:0;background:#ffF;font:bold 13px Arial}
        '''span.c1 {cursor:hand;color:black;width:30;height:16;text-align:center;margin-top:0;background:#ffF;font:bold 13px Arial}
        '''span.c2 {cursor:hand;color:red;width:30;height:16;text-align:center;margin-top:0;background:#ffF;font:bold 13px Arial}
        '''span.c3 {cursor:hand;color:#b0b0b0;width:30;height:16;text-align:center;margin-top:0;background:#ffF;font:bold 12px Arial}
        '''&lt;/style&gt; [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Calendar() As String
            Get
                Return ResourceManager.GetString("Calendar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à // Paste this code into the HEAD section of your HTML document.
        '''
        '''function bgChange() {
        '''  document.bgColor=document.getElementById(&quot;f&quot;).txt.value;
        '''}
        '''
        '''// Paste this code into the BODY section of your HTML document
        '''
        '''
        '''&lt;form id=&quot;f&quot;&gt;
        '''Enter new background color: &lt;input type=&quot;text&quot; name=&quot;txt&quot;&gt;
        '''&lt;input type=&quot;submit&quot; value=&quot;Change color&quot; onclick=&quot;bgChange(); return false;&quot;&gt;
        '''&lt;/form&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property Change_Background_Colors() As String
            Get
                Return ResourceManager.GetString("Change_Background_Colors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;body&gt;
        '''
        '''&lt;h2&gt;Unordered List with Square Bullets&lt;/h2&gt;
        '''
        '''&lt;ul style=&quot;list-style-type:square&quot;&gt;
        '''  &lt;li&gt;Coffee&lt;/li&gt;
        '''  &lt;li&gt;Tea&lt;/li&gt;
        '''  &lt;li&gt;Milk&lt;/li&gt;
        '''&lt;/ul&gt;
        '''
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property Circle() As String
            Get
                Return ResourceManager.GetString("Circle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à /* This script and many more are available free online at
        '''The JavaScript Source!! http://www.javascriptsource.com
        '''Created by: Konstantin Jagello | http://javascript-array.com/ */
        '''
        '''function getClientWidth() {
        '''  return document.compatMode==&apos;CSS1Compat&apos; &amp;&amp; !window.opera?document.documentElement.clientWidth:document.body.clientWidth;
        '''}
        '''
        '''function getClientHeight() {
        '''  return document.compatMode==&apos;CSS1Compat&apos; &amp;&amp; !window.opera?document.documentElement.clientHeight:document.body.clientHeight;
        '''}
        '''
        '''//Paste [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Client_Window_Size() As String
            Get
                Return ResourceManager.GetString("Client_Window_Size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;form&gt;
        '''&lt;input type=button value=&quot;Close Window&quot; onClick=&quot;javascript:window.close();&quot;&gt;
        '''&lt;/form&gt; 
        '''For a text link, paste the following where you want the link to appear:
        '''&lt;a href=&quot;javascript:window.close();&quot;&gt;Click to Close Window&lt;/a&gt;
        '''To make the window close after a given number of seconds, add the event handler to the &lt;body&gt; tag. FYI, 20000 equals 20 seconds.
        '''&lt;BODY onLoad=&quot;setTimeout(window.close,20000)&quot;&gt;
        '''
        '''//Source : http://www.htmlgoodies.com/beyond/javascript/article.php/3887346/Top-10-JavaScript-Snip [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Close_Window() As String
            Get
                Return ResourceManager.GetString("Close_Window", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;body&gt;
        '''
        '''&lt;p&gt;
        '''Depending on browser support:&lt;br&gt;
        '''A color picker can pop-up when you enter the input field.
        '''&lt;/p&gt;
        '''
        '''&lt;form action=&quot;/action_page.php&quot;&gt;
        '''  Select your favorite color:
        '''  &lt;input type=&quot;color&quot; name=&quot;favcolor&quot; value=&quot;#ff0000&quot;&gt;
        '''  &lt;input type=&quot;submit&quot;&gt;
        '''&lt;/form&gt;
        '''
        '''&lt;p&gt;&lt;b&gt;Note:&lt;/b&gt; type=&quot;color&quot; is not supported in Internet Explorer 11 and earlier versions or Safari 9.1 and earlier versions.&lt;/p&gt;
        '''
        '''&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property Color_Selection() As String
            Get
                Return ResourceManager.GetString("Color_Selection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Copy_6524() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copy_6524", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;SCRIPT LANGUAGE=&quot;JavaScript&quot;&gt;
        '''function copyit(theField) {
        '''	var selectedText = document.selection;
        '''	if (selectedText.type == &apos;Text&apos;) {
        '''		var newRange = selectedText.createRange();
        '''		theField.focus();
        '''		theField.value = newRange.text;
        '''	} else {
        '''		alert(&apos;select a text in the page and then press this button&apos;);
        '''	}
        '''}
        '''&lt;/script&gt;
        '''//And in the body of your web page, add the following where you want the text to appear:
        '''
        '''&lt;form name=&quot;it&quot;&gt;
        '''&lt;div align=&quot;center&quot;&gt;
        '''&lt;input onclick=&quot;copyit(this.form.select1)&quot; t [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Copy_Selected_Text() As String
            Get
                Return ResourceManager.GetString("Copy_Selected_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cut_6523() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cut_6523", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;SCRIPT LANGUAGE=&quot;JavaScript&quot;&gt;
        '''var now = new Date();
        '''
        '''var days = new Array(&apos;Sunday&apos;,&apos;Monday&apos;,&apos;Tuesday&apos;,&apos;Wednesday&apos;,&apos;Thursday&apos;,&apos;Friday&apos;,&apos;Saturday&apos;);
        '''
        '''var months = new Array(&apos;January&apos;,&apos;February&apos;,&apos;March&apos;,&apos;April&apos;,&apos;May&apos;,&apos;June&apos;,&apos;July&apos;,&apos;August&apos;,&apos;September&apos;,&apos;October&apos;,&apos;November&apos;,&apos;December&apos;);
        '''
        '''var date = ((now.getDate()&lt;10) ? &quot;0&quot; : &quot;&quot;)+ now.getDate();
        '''
        '''function fourdigits(number)	{
        '''	return (number &lt; 1000) ? number + 1900 : number;
        '''								}
        '''today =  days[now.getDay()] + &quot;, &quot; +
        '''         months[now.getMont [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Date_Display() As String
            Get
                Return ResourceManager.GetString("Date_Display", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à //Created by: David Walsh
        '''var is_chrome = navigator.userAgent.toLowerCase().indexOf(&apos;chrome&apos;) &gt; -1;
        '''// Source : http://www.javascriptsource.com/snippets/detecting-google-chrome.html.
        '''</summary>
        Friend ReadOnly Property Detecting_Google_Chrome() As String
            Get
                Return ResourceManager.GetString("Detecting_Google_Chrome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;ol&gt;
        '''  &lt;li&gt;Coffee&lt;/li&gt;
        '''  &lt;li&gt;Tea&lt;/li&gt;
        '''  &lt;li&gt;Milk&lt;/li&gt;
        '''&lt;/ol&gt;.
        '''</summary>
        Friend ReadOnly Property Disc() As String
            Get
                Return ResourceManager.GetString("Disc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;body&gt;
        '''
        '''&lt;h1&gt;My First Heading&lt;/h1&gt;
        '''&lt;p&gt;My first paragraph.&lt;/p&gt;
        '''
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property Documents() As String
            Get
                Return ResourceManager.GetString("Documents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property drg_drop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("drg_drop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;select name=&quot;cars&quot;&gt;
        '''  &lt;option value=&quot;volvo&quot;&gt;Volvo&lt;/option&gt;
        '''  &lt;option value=&quot;saab&quot;&gt;Saab&lt;/option&gt;
        '''  &lt;option value=&quot;fiat&quot;&gt;Fiat&lt;/option&gt;
        '''  &lt;option value=&quot;audi&quot;&gt;Audi&lt;/option&gt;
        '''&lt;/select&gt;.
        '''</summary>
        Friend ReadOnly Property drop_down_list() As String
            Get
                Return ResourceManager.GetString("drop_down_list", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''  &lt;link rel=&quot;stylesheet&quot; href=&quot;styles.css&quot;&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''
        '''&lt;h1&gt;This is a heading&lt;/h1&gt;
        '''&lt;p&gt;This is a paragraph.&lt;/p&gt;
        '''
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property External() As String
            Get
                Return ResourceManager.GetString("External", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;BODY OnLoad=&quot;document.nameform.user.focus();&quot;&gt;
        '''// Source : http://www.htmlgoodies.com/beyond/javascript/article.php/3887346/Top-10-JavaScript-Snippets-for-Common-Tasks.htm.
        '''</summary>
        Friend ReadOnly Property Focus_OnLoad() As String
            Get
                Return ResourceManager.GetString("Focus_OnLoad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;style&gt;
        '''h1 {
        '''    color: blue;
        '''    font-family: verdana;
        '''    font-size: 300%;
        '''}
        '''p  {
        '''    color: red;
        '''    font-family: courier;
        '''    font-size: 160%;
        '''}
        '''&lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''
        '''&lt;h1&gt;This is a heading&lt;/h1&gt;
        '''&lt;p&gt;This is a paragraph.&lt;/p&gt;
        '''
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property Fonts() As String
            Get
                Return ResourceManager.GetString("Fonts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;h1&gt;This is heading 1&lt;/h1&gt;
        '''&lt;h2&gt;This is heading 2&lt;/h2&gt;
        '''&lt;h3&gt;This is heading 3&lt;/h3&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property Headings() As String
            Get
                Return ResourceManager.GetString("Headings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à 
        '''//Paste this code into an external JavaScript file named: historyKeeper.js
        '''/* This script and many more are available free online at
        '''The JavaScript Source!! http://www.javascriptsource.com
        '''Created by: Kevin Newman | http://www.unfocus.com/projects/HistoryKeeper/
        '''version 1.9.3 (alpha) (2007/02/13
        '''Licensed under: Creative Commons License */
        '''
        '''
        '''// if (typeof unFocus == &quot;undefined&quot;) var unFocus = {};
        '''
        '''/* 	Class: unFocus.History
        '''		A singleton with subscriber interface (&lt;unFocus.Utilities.EventManager [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property History_Keeper() As String
            Get
                Return ResourceManager.GetString("History_Keeper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Home_5699() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Home_5699", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;a href=&quot;default.asp&quot;&gt;
        '''  &lt;img src=&quot;smiley.gif&quot; alt=&quot;HTML tutorial&quot; style=&quot;width:42px;height:42px;border:0;&quot;&gt;
        '''&lt;/a&gt;.
        '''</summary>
        Friend ReadOnly Property Image_as_Link() As String
            Get
                Return ResourceManager.GetString("Image_as_Link", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;img src=&quot;w3schools.jpg&quot; alt=&quot;W3Schools.com&quot; width=&quot;104&quot; height=&quot;142&quot;&gt;.
        '''</summary>
        Friend ReadOnly Property Images() As String
            Get
                Return ResourceManager.GetString("Images", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;img src=&quot;url&quot; alt=&quot;some_text&quot; style=&quot;width:width;height:height;&quot;&gt;.
        '''</summary>
        Friend ReadOnly Property Images_Syntax() As String
            Get
                Return ResourceManager.GetString("Images_Syntax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;style&gt;
        '''body {background-color: powderblue;}
        '''h1   {color: blue;}
        '''p    {color: red;}
        '''&lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''
        '''&lt;h1&gt;This is a heading&lt;/h1&gt;
        '''&lt;p&gt;This is a paragraph.&lt;/p&gt;
        '''
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property Internal() As String
            Get
                Return ResourceManager.GetString("Internal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;SCRIPT LANGUAGE=&quot;JavaScript&quot;&gt;
        '''var ip = &apos;&lt;!--#echo var=&quot;REMOTE_ADDR&quot;--&gt;&apos;;
        '''document.write(&quot;Your IP address is&quot; + ip);
        '''&lt;/script&gt;
        '''// Source : http://www.htmlgoodies.com/beyond/javascript/article.php/3887346/Top-10-JavaScript-Snippets-for-Common-Tasks.htm.
        '''</summary>
        Friend ReadOnly Property IP_Address() As String
            Get
                Return ResourceManager.GetString("IP_Address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;body&gt;
        '''
        '''&lt;p&gt;This is&lt;br&gt;a paragraph&lt;br&gt;with line breaks&lt;/p&gt;
        '''
        '''&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property Line_Breaks() As String
            Get
                Return ResourceManager.GetString("Line_Breaks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à .
        '''</summary>
        Friend ReadOnly Property Link_Colors() As String
            Get
                Return ResourceManager.GetString("Link_Colors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;a href=&quot;https://www.w3schools.com&quot;&gt;This is a link&lt;/a&gt;.
        '''</summary>
        Friend ReadOnly Property Links() As String
            Get
                Return ResourceManager.GetString("Links", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loadingAnimation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loadingAnimation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;a href=&quot;html_images.asp&quot;&gt;HTML Images&lt;/a&gt;.
        '''</summary>
        Friend ReadOnly Property Local_Links() As String
            Get
                Return ResourceManager.GetString("Local_Links", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;body&gt;
        '''
        '''&lt;form action=&quot;/action_page.php&quot;&gt;
        '''  First name:&lt;br&gt;
        '''  &lt;input type=&quot;text&quot; value=&quot;Mickey&quot;&gt;
        '''  &lt;br&gt;
        '''  Last name:&lt;br&gt;
        '''  &lt;input type=&quot;text&quot; name=&quot;lastname&quot; value=&quot;Mouse&quot;&gt;
        '''  &lt;br&gt;&lt;br&gt;
        '''  &lt;input type=&quot;submit&quot; value=&quot;Submit&quot;&gt;
        '''&lt;/form&gt; 
        '''
        '''&lt;p&gt;If you click the &quot;Submit&quot; button, the form-data will be sent to a page called &quot;/action_page.php&quot;.&lt;/p&gt;
        '''
        '''&lt;p&gt;Notice that the value of the &quot;First name&quot; field will not be submitted, because the input element does not have a name attribute.&lt;/p&gt; [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Login() As String
            Get
                Return ResourceManager.GetString("Login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à p {
        '''    border 1px solid powderblue;
        '''    margin 50px;
        '''}.
        '''</summary>
        Friend ReadOnly Property Margin() As String
            Get
                Return ResourceManager.GetString("Margin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;body&gt;
        '''
        '''&lt;input type=&quot;button&quot; onclick=&quot;alert(&apos;Hello World!&apos;)&quot; value=&quot;Click Me!&quot;&gt;
        '''
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property Message_Box() As String
            Get
                Return ResourceManager.GetString("Message_Box", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NavigateBackwards_6270() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavigateBackwards_6270", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NavigateForward_6271() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavigateForward_6271", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;body&gt;
        '''
        '''&lt;h2&gt;An ordered HTML list&lt;/h2&gt;
        '''
        '''&lt;ol&gt;
        '''  &lt;li&gt;Coffee&lt;/li&gt;
        '''  &lt;li&gt;Tea&lt;/li&gt;
        '''  &lt;li&gt;Milk&lt;/li&gt;
        '''&lt;/ol&gt;  
        '''
        '''&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property Numbers() As String
            Get
                Return ResourceManager.GetString("Numbers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à p {
        '''    border: 1px solid powderblue;
        '''    padding: 30px;
        '''}.
        '''</summary>
        Friend ReadOnly Property Padding() As String
            Get
                Return ResourceManager.GetString("Padding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;p&gt;This is a paragraph.&lt;/p&gt;
        '''&lt;p&gt;This is another paragraph.&lt;/p&gt;.
        '''</summary>
        Friend ReadOnly Property Paragraphs() As String
            Get
                Return ResourceManager.GetString("Paragraphs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à 
        '''/ **
        '''GENERATING FUNCTION OF A RANDOM PASSWORD
        '''IN JAVASCRIPT
        '''AUTHOR OF THE SCRIPT: HOLDZ
        '''DATE OF OUTPUT: 12/04/15
        '''CODE:
        '''*
        '''// Source : http://codes-sources.commentcamarche.net/source/100984-generateur-de-mot-de-passe-en-javascript
        '''
        '''*
        '''**/
        '''
        '''function genere_mdp(nombreCaracteres,activateMAJ, activateMin,activateNumber)
        '''{
        '''  var array = &quot;&quot;, rand_pass = &quot;&quot;;
        '''  if(activateMAJ)
        '''  {
        '''    array += &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;;
        '''  }
        '''  if(activateMin)
        '''  {
        '''    array += &quot;abcdefghijklmnopqrstuvwxyz&quot;;
        '''  } [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Pass_genert() As String
            Get
                Return ResourceManager.GetString("Pass_genert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Paste_6520() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paste_6520", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property play_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;object width=&quot;400&quot; height=&quot;50&quot; data=&quot;bookmark.swf&quot;&gt;&lt;/object&gt;.
        '''</summary>
        Friend ReadOnly Property Plug_ins() As String
            Get
                Return ResourceManager.GetString("Plug_ins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;body&gt;
        '''
        '''&lt;p&gt;The pre tag preserves both spaces and line breaks:&lt;/p&gt;
        '''
        '''&lt;pre&gt;
        '''   My Bonnie lies over the ocean.
        '''
        '''   My Bonnie lies over the sea.
        '''
        '''   My Bonnie lies over the ocean.
        '''   
        '''   Oh, bring back my Bonnie to me.
        '''&lt;/pre&gt;
        '''
        '''&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property Poem() As String
            Get
                Return ResourceManager.GetString("Poem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à //Created by: Jeff Johnson
        '''//Source : http://www.javascriptsource.com/snippets/popup-blocker-detection-2.html
        '''function detectPopupBlocker() {
        '''		var test = window.open(null,&quot;&quot;,&quot;width=100,height=100&quot;);
        '''		try {
        '''				test.close();
        '''				alert(&quot;Pop-ups not blocked.&quot;);
        '''		} catch (e) {
        '''				alert(&quot;Pop-ups blocked.&quot;);
        '''		}
        '''}
        '''
        '''// Created by: Simon Willison
        '''// http://simon.incutio.com/archive/2004/05/26/addLoadEvent
        '''function addLoadEvent(func) {
        '''  var oldonload = window.onload;
        '''  if (typeof window.onload ! [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property Popup_Blocker_Detection_2() As String
            Get
                Return ResourceManager.GetString("Popup_Blocker_Detection_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;form&gt;
        '''  &lt;input type=&quot;radio&quot; name=&quot;gender&quot; value=&quot;male&quot; checked&gt; Male&lt;br&gt;
        '''  &lt;input type=&quot;radio&quot; name=&quot;gender&quot; value=&quot;female&quot;&gt; Female&lt;br&gt;
        '''  &lt;input type=&quot;radio&quot; name=&quot;gender&quot; value=&quot;other&quot;&gt; Other
        '''&lt;/form&gt;.
        '''</summary>
        Friend ReadOnly Property Radio_buttons() As String
            Get
                Return ResourceManager.GetString("Radio_buttons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Save_6530() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save_6530", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Saveall_6518() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Saveall_6518", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SelectCell_363_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectCell_363_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;a href=&quot;url&quot;&gt;link text&lt;/a&gt;.
        '''</summary>
        Friend ReadOnly Property Simple_Link() As String
            Get
                Return ResourceManager.GetString("Simple_Link", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;body&gt;
        '''
        '''&lt;iframe width=&quot;420&quot; height=&quot;345&quot; src=&quot;https://www.youtube.com/embed/XGSy3_Czz8k&quot;&gt;
        '''&lt;/iframe&gt;
        '''
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property Simple_Video() As String
            Get
                Return ResourceManager.GetString("Simple_Video", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;SCRIPT LANGUAGE=&quot;JavaScript&quot;&gt;
        '''var allowedreferrer = &quot;http://www.yoursite.com/referringpagename.htm&quot;; 
        '''if (document.referrer.indexOf(allowedreferrer) == -1) {
        '''alert(&quot;You can only access this page from &quot; + allowedreferrer);
        '''window.location=allowedreferrer;
        '''}
        '''&lt;/script&gt;
        '''// Source : http://www.htmlgoodies.com/beyond/javascript/article.php/3887346/Top-10-JavaScript-Snippets-for-Common-Tasks.htm.
        '''</summary>
        Friend ReadOnly Property Specify_Referring_Page() As String
            Get
                Return ResourceManager.GetString("Specify_Referring_Page", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;body&gt;
        '''
        '''&lt;h2&gt;Unordered List with Square Bullets&lt;/h2&gt;
        '''
        '''&lt;ul style=&quot;list-style-type:square&quot;&gt;
        '''  &lt;li&gt;Coffee&lt;/li&gt;
        '''  &lt;li&gt;Tea&lt;/li&gt;
        '''  &lt;li&gt;Milk&lt;/li&gt;
        '''&lt;/ul&gt;
        '''
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property Square_Bullets() As String
            Get
                Return ResourceManager.GetString("Square_Bullets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;style&gt;
        '''table, th, td {
        '''    border: 1px solid black;
        '''    border-collapse: collapse;
        '''}
        '''th, td {
        '''    padding: 5px;
        '''    text-align: left;    
        '''}
        '''&lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''
        '''&lt;h2&gt;Cell that spans two columns:&lt;/h2&gt;
        '''&lt;table style=&quot;width:100%&quot;&gt;
        '''  &lt;tr&gt;
        '''    &lt;th&gt;Name&lt;/th&gt;
        '''    &lt;th colspan=&quot;2&quot;&gt;Telephone&lt;/th&gt;
        '''  &lt;/tr&gt;
        '''  &lt;tr&gt;
        '''    &lt;td&gt;Bill Gates&lt;/td&gt;
        '''    &lt;td&gt;55577854&lt;/td&gt;
        '''    &lt;td&gt;55577855&lt;/td&gt;
        '''  &lt;/tr&gt;
        '''&lt;/table&gt;
        '''
        '''&lt;/body&gt;
        '''&lt;/html&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property Table() As String
            Get
                Return ResourceManager.GetString("Table", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;textarea name=&quot;message&quot; rows=&quot;10&quot; cols=&quot;30&quot;&gt;
        '''The cat was playing in the garden.
        '''&lt;/textarea&gt;.
        '''</summary>
        Friend ReadOnly Property Textarea() As String
            Get
                Return ResourceManager.GetString("Textarea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;video width=&quot;320&quot; height=&quot;240&quot; controls&gt;
        '''  &lt;source src=&quot;movie.mp4&quot; type=&quot;video/mp4&quot;&gt;
        '''  &lt;source src=&quot;movie.ogg&quot; type=&quot;video/ogg&quot;&gt;
        '''Your browser does not support the video tag.
        '''&lt;/video&gt;.
        '''</summary>
        Friend ReadOnly Property Video() As String
            Get
                Return ResourceManager.GetString("Video", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à 
        '''&lt;!--  Place this snippet in the body tag of the popup window.  --&gt;
        '''
        '''
        '''onLoad=&quot;setTimeout(&apos;window.close()&apos;, 5000);&quot;
        '''
        '''
        '''//Source : http://www.javascriptsource.com/snippets/window-close-automatically.html.
        '''</summary>
        Friend ReadOnly Property Window_Close_Automatically() As String
            Get
                Return ResourceManager.GetString("Window_Close_Automatically", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
