'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property drk_theme() As Boolean
            Get
                Return CType(Me("drk_theme"),Boolean)
            End Get
            Set
                Me("drk_theme") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property wth_theme() As Boolean
            Get
                Return CType(Me("wth_theme"),Boolean)
            End Get
            Set
                Me("wth_theme") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property custo_theme() As Boolean
            Get
                Return CType(Me("custo_theme"),Boolean)
            End Get
            Set
                Me("custo_theme") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Custo_color() As Char
            Get
                Return CType(Me("Custo_color"),Char)
            End Get
            Set
                Me("Custo_color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Last_Save_Path() As String
            Get
                Return CType(Me("Last_Save_Path"),String)
            End Get
            Set
                Me("Last_Save_Path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastText() As String
            Get
                Return CType(Me("LastText"),String)
            End Get
            Set
                Me("LastText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property txtbox_Showlinenumber() As Boolean
            Get
                Return CType(Me("txtbox_Showlinenumber"),Boolean)
            End Get
            Set
                Me("txtbox_Showlinenumber") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Teal")>  _
        Public Property txtbox_linenmbrcol() As Global.System.Drawing.Color
            Get
                Return CType(Me("txtbox_linenmbrcol"),Global.System.Drawing.Color)
            End Get
            Set
                Me("txtbox_linenmbrcol") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("45, 45, 48")>  _
        Public Property txtbox_forecolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("txtbox_forecolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("txtbox_forecolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property txtbox_bkcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("txtbox_bkcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("txtbox_bkcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property txtbox_bokmarkcol() As Global.System.Drawing.Color
            Get
                Return CType(Me("txtbox_bokmarkcol"),Global.System.Drawing.Color)
            End Get
            Set
                Me("txtbox_bokmarkcol") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60, 0, 0, 255")>  _
        Public Property txtbox_selcol() As Global.System.Drawing.Color
            Get
                Return CType(Me("txtbox_selcol"),Global.System.Drawing.Color)
            End Get
            Set
                Me("txtbox_selcol") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Silver")>  _
        Public Property txtbox_servlcol() As Global.System.Drawing.Color
            Get
                Return CType(Me("txtbox_servlcol"),Global.System.Drawing.Color)
            End Get
            Set
                Me("txtbox_servlcol") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property txtbox_showscrlbar() As Boolean
            Get
                Return CType(Me("txtbox_showscrlbar"),Boolean)
            End Get
            Set
                Me("txtbox_showscrlbar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property txtbox_showfldgnline() As Boolean
            Get
                Return CType(Me("txtbox_showfldgnline"),Boolean)
            End Get
            Set
                Me("txtbox_showfldgnline") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property m() As Decimal
            Get
                Return CType(Me("m"),Decimal)
            End Get
            Set
                Me("m") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CurrentLineC() As Boolean
            Get
                Return CType(Me("CurrentLineC"),Boolean)
            End Get
            Set
                Me("CurrentLineC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("HTML")>  _
        Public Property txtbox_lang() As String
            Get
                Return CType(Me("txtbox_lang"),String)
            End Get
            Set
                Me("txtbox_lang") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property txtbox_brodr() As String
            Get
                Return CType(Me("txtbox_brodr"),String)
            End Get
            Set
                Me("txtbox_brodr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Frm_Lock() As Boolean
            Get
                Return CType(Me("Frm_Lock"),Boolean)
            End Get
            Set
                Me("Frm_Lock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Frm_LokePass() As String
            Get
                Return CType(Me("Frm_LokePass"),String)
            End Get
            Set
                Me("Frm_LokePass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Frm_hidWhenClosed() As Boolean
            Get
                Return CType(Me("Frm_hidWhenClosed"),Boolean)
            End Get
            Set
                Me("Frm_hidWhenClosed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HideWhenmini() As Boolean
            Get
                Return CType(Me("HideWhenmini"),Boolean)
            End Get
            Set
                Me("HideWhenmini") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Frm_Starthiden() As Boolean
            Get
                Return CType(Me("Frm_Starthiden"),Boolean)
            End Get
            Set
                Me("Frm_Starthiden") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property frm_startup() As Boolean
            Get
                Return CType(Me("frm_startup"),Boolean)
            End Get
            Set
                Me("frm_startup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property frm_savewhenclosed() As Boolean
            Get
                Return CType(Me("frm_savewhenclosed"),Boolean)
            End Get
            Set
                Me("frm_savewhenclosed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property frm_Opacity() As Integer
            Get
                Return CType(Me("frm_Opacity"),Integer)
            End Get
            Set
                Me("frm_Opacity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Frm_Topmost() As Boolean
            Get
                Return CType(Me("Frm_Topmost"),Boolean)
            End Get
            Set
                Me("Frm_Topmost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property darkthem() As Boolean
            Get
                Return CType(Me("darkthem"),Boolean)
            End Get
            Set
                Me("darkthem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property WhitTheme() As Boolean
            Get
                Return CType(Me("WhitTheme"),Boolean)
            End Get
            Set
                Me("WhitTheme") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property teststr() As String
            Get
                Return CType(Me("teststr"),String)
            End Get
            Set
                Me("teststr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property txtbox_paddingback() As Global.System.Drawing.Color
            Get
                Return CType(Me("txtbox_paddingback"),Global.System.Drawing.Color)
            End Get
            Set
                Me("txtbox_paddingback") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Opacty() As Integer
            Get
                Return CType(Me("Opacty"),Integer)
            End Get
            Set
                Me("Opacty") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.TryHTML.My.MySettings
            Get
                Return Global.TryHTML.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
